version: '2'

services:

  paperbadger:
    image: node:6
    command: bash -c 'cd /src && (if [ ! -d "node_modules" ]; then npm install && chmod -R uo+w node_modules; fi) && npm start'
    ports:
      - 5000:5000
    volumes:
      - .:/src
    environment:
      - MONGOLAB_URI=mongodb://mongo:27017/test
      - REDISCLOUD_URL=redis://redis:6379/0

  mongo:
    image: mongo:2
    # volumes:    # to persist database between runs
    #   - /data/db

  redis:
    image: redis
